[package]
name = "c"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.1.5", features = [ "cargo" ] }
termion = "1.5.6"
dirs = "4.0.0"
dlopen = "0.1.8"
dlopen_derive = "0.1.4"

